<style scoped>
    .b-create-ad-page {font-family: Helvetica Neue,Helvetica,Arial,sans-serif;
    color: #464b4f;
    font-size: 13px;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    align-items: center;
    display: flex;
    height: 100%;
    justify-content: center;}
            </style>

<template>    
<div class="b-create-ad-page"><div style="transition-delay: 0s; display: none;"><div class="b-bouncing-loader spinner-absolute h-pt-40" style="bottom: auto;"><div></div><div></div><div></div></div></div> <div class="b-create-ad-page__create-ad-card-wrapper"><div class="b-create-ad-card"><div class="b-create-ad-card__header-wrapper"><div class="b-create-ad-card-header h-flex-center h-mb-15"><div class="b-create-ad-card-header__button"><!----></div> <div class="b-create-ad-card-header__title h-flex-1-0">
    Post ad
  </div> <div class="b-create-ad-card-header__button"><button type="button" class="b-create-ad-card-header__button-clear qa-clear-all-fields-button fw-button qa-fw-button fw-button--type-primary-link-like fw-button--size-small b-create-ad-card-header__button-clear--disabled" disabeld="true"><span class="fw-button__content"><!----> <span class="fw-button__slot-wrapper">
      Clear
    </span></span></button></div></div></div> <form class="b-create-ad-card__form"><div class="b-create-ad-card__form-tile"><div class="b-create-ad-card__form-about"><div class="b-create-ad-card__category-attributes"><div class="b-create-ad-card__form-about-row"><div class="b-category-section h-width-100p"><div class="fw-field-container qa-fw-field-container h-width-100p"><div class="fw-field fw-selection"><!---->  <div class="fw-field__field-content"><div class="fw-field__content"><label>
        Category*
      </label> <div class="fw-select qa-fw-select b-category-section__category-select qa-choose-category"><div tabindex="-1" role="combobox" aria-owns="listbox-null" class="multiselect qa-multiselect multiselect--no-clearable"><div class="multiselect__select"></div>  <div class="multiselect__tags"><div class="multiselect__tags-wrap" style="display: none;"></div> <!----> <div class="multiselect__spinner" style="display: none;"></div> <input name="parent_category" type="text" autocomplete="off" spellcheck="false" placeholder="" tabindex="0" aria-controls="listbox-null" class="multiselect__input" style="width: 0px; position: absolute; padding: 0px;"> <!----> <span class="multiselect__placeholder">
          
        </span></div> <div tabindex="-1" class="multiselect__content-wrapper" style="max-height: 600px; display: none;"><ul role="listbox" id="listbox-null" class="multiselect__content" style="display: inline-block;"> <!----> <li id="null-0" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option multiselect__option--highlight"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/agriculture.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Agriculture &amp; Food
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-1" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/babies.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Babies &amp; Kids
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-2" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/equipment.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Commercial Equipment &amp; Tools
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-3" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/electronics.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Electronics
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-4" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/fashion.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Fashion
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-5" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/beauty.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Health &amp; Beauty
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-6" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/home.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Home, Furniture &amp; Appliances
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-7" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/jobs.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Jobs
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-8" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/mobile.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Mobile Phones &amp; Tablets
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-9" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/animals.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Pets
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-10" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/real-estate.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Property
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-11" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/repair.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Repair &amp; Construction
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-12" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/jobseekers.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Seeking Work CVs
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-13" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/services.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Services
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-14" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/hobbies.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Sports, Arts &amp; Outdoors
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-15" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><div class="fw-select__option-image"><img src="https://assets.jijistatic.net/art/attributes/categories/vehicles.png" width="32" height="32"></div> <div class="fw-select__option-label">
            Vehicles
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li> <li style="display: none;"><span class="multiselect__option"><span></span></span></li> <li style="display: none;"><span class="multiselect__option"><span></span></span></li> </ul></div></div> <!----></div></div></div>  <!----> <!----> <!----> <!----></div>  <!----></div></div> <!----></div> <div class="b-create-ad-card__form-about-row"><div class="b-region-section h-width-100p"><div class="fw-field-container qa-fw-field-container h-width-100p"><div class="fw-field fw-disabled fw-selection"><!---->  <div class="fw-field__field-content"><div class="fw-field__content"><label>
        Select Location*
      </label> <div class="fw-select qa-fw-select qa-choose-region"><div tabindex="-1" role="combobox" aria-owns="listbox-null" class="multiselect qa-multiselect multiselect--disabled multiselect--no-clearable"><div class="multiselect__select"></div>  <div class="multiselect__tags"><div class="multiselect__tags-wrap" style="display: none;"></div> <!----> <div class="multiselect__spinner" style="display: none;"></div> <input name="parent_region" type="text" autocomplete="off" spellcheck="false" placeholder=""  key="disabled" tabindex="0" aria-controls="listbox-null" class="multiselect__input" style="width: 0px; position: absolute; padding: 0px;"> <!----> <span class="multiselect__placeholder">
        C:\Users\Donchichi\Documents\Old J.efocus Tech\modal-project
        </span></div> <div tabindex="-1" class="multiselect__content-wrapper" style="max-height: 600px; display: none;"><ul role="listbox" id="listbox-null" class="multiselect__content" style="display: inline-block;"> <!----> <li id="null-0" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option multiselect__option--highlight"><div class="fw-select__block-label">
        Popular Locations
      </div> <!----> <div class="fw-select__option fw-select__option--has-label"><!----> <div class="fw-select__option-label">
            Abuja (FCT)
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-1" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Lagos State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-2" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Ogun State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-3" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Oyo State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-4" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Rivers State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-5" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <div class="fw-select__block-label">
        Other Locations
      </div> <div class="fw-select__option fw-select__option--has-label"><!----> <div class="fw-select__option-label">
            Abia State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-6" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Adamawa State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-7" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Akwa Ibom State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-8" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Anambra State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-9" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Bauchi State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-10" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Bayelsa State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-11" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Benue State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-12" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Borno State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-13" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Cross River State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-14" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Delta State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-15" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Ebonyi State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-16" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Edo State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-17" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Ekiti State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-18" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Enugu State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-19" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Gombe State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-20" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Imo State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-21" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Jigawa State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-22" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Kaduna State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-23" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Kano State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-24" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Katsina State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-25" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Kebbi State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-26" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Kogi State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-27" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Kwara State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-28" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Nasarawa State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-29" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Niger State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-30" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Ondo State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-31" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Osun State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-32" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Plateau State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-33" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Sokoto State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-34" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Taraba State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-35" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Yobe State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li><li id="null-36" role="option" class="multiselect__element"><span data-select="" data-selected="" data-deselect="Press to remove" class="multiselect__option"><!----> <!----> <div class="fw-select__option"><!----> <div class="fw-select__option-label">
            Zamfara State
          </div> <svg width="10px" height="16px" color="#EBF2F7" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-arrow-right"></use></svg> <!----></div></span> <!----></li> <li style="display: none;"><span class="multiselect__option"><span></span></span></li> <li style="display: none;"><span class="multiselect__option"><span></span></span></li> </ul></div></div> <!----></div></div></div>  <!----> <!----> <!----> <!----></div>  <!----></div></div></div></div> <div class="b-create-ad-card__photos-section"><div class="b-add-image-section qa-b-add-image-section b-add-image-section--disabled"><div class="b-add-image-section__title h-mb-5">
    Add photo
  </div> <div class="b-add-image-section__body"><div class="b-add-image-section__static-hints h-mb-5"><!---->
      First picture - is the title picture.
      <span>
        You can change the order of photos: just grab your photos and drag
      </span></div> <!----> <div class="b-add-image-section__photos-wrapper"><label><label class="b-app-image-reader b-app-image-reader--disabled"><div class="b-add-image-section__file-input-button"><svg width="14px" height="14px" color="#00B53F" xmlns="http://www.w3.org/2000/svg" class="icon sprite-icons"><use href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-add" xlink:href="/_nuxt/2c6964b9a34a7dbd66aca77e616705d3.svg#i-add"></use></svg></div> <input  name="image" type="file" accept="image/*" class="qa-messenger-send-image"></label></label> <!----></div> <div class="b-add-image-section__static-hints h-mt-5">
      Supported formats are *.jpg and *.png
    </div> </div></div></div> <!----> <div class="b-create-ad-card__submit-button__wrapper"><button type="button" class="b-create-ad-card__next-button h-width-100p fw-button qa-fw-button fw-button--type-bloated-success-grey-disabled fw-button--size-medium fw-button--disabled"><span class="fw-button__content"><!----> <span class="fw-button__slot-wrapper">
              Next
            </span></span></button></div></div></div> <div style="display: none;"><div class="b-create-ad-card__form-tile"><!----> <div class="b-create-ad-card__form-attributes"><div class="b-form-attributes row qa-b-form-attributes"> <!----></div></div></div> <!----> <!----> <div class="b-create-ad-card__form-tile"><!----> <div class="b-create-ad-card__form-submit"><button type="submit" class="b-create-ad-card__submit-button qa-submit-button fw-button qa-fw-button fw-button--type-bloated-success-grey-disabled fw-button--size-large" id="submit_button"><span class="fw-button__content"><!----> <span class="fw-button__slot-wrapper"><span>
                Post ad
              </span></span></span></button> <div class="b-create-ad-card__rules-text h-mt-15">
              By clicking on Post Ad, you accept the
              <a href="/rules.html" class="">
                Terms of Use
              </a>
              , confirm that you will abide by the Safety Tips, and declare that this posting does not include any Prohibited Items.
            </div></div></div></div></form> <!----> <!----> <!----> <!----> <!----> <!----></div></div></div>
            
            </template>

<script>


export default {
    data() {
        
    },

}
</script>

            